defaults:
  - hydra: default
  - modelpool: clip-vit-base-patch32_TA8
  - method: simple_average
  - _self_

fast_dev_run: false # Run a single batch of data to test the model or method
print_config: true # Print the configuration to the console

