_target_: fusion_bench.modelpool.CausalLMPool

pretrained_model_name_or_path: meta-llama/Llama-3.2-1B-Instruct

models:
  _pretrained_:
    _target_: fusion_bench.modelpool.seq_classification_lm.create_reward_model_from_pretrained
    pretrained_model_name_or_path: ${...pretrained_model_name_or_path}
    torch_dtype: bfloat16

tokenizer:
  _target_: transformers.AutoTokenizer.from_pretrained
  pretrained_model_name_or_path: ${..pretrained_model_name_or_path}

train_datasets:
  preference_700k:
    _target_: fusion_bench.dataset.llama.preference_700k.load_tokenized_preference_700k_for_bradley_terry_rm
    tokenizer: ${...tokenizer}
    path: hendrydong/preference_700K
    split: train
    cache_path: null
